### ISSUE TITLE
Random MathJax rendering of ordinary text

### ISSUE THREAD

**Issue by calaveraInfo** [markserv/markserv#15]
MathJax randomly selects portion of ordinary text and renders it as math. I really couldn't find any clue for what is the decision process behind this as it seems to be truly random. Is it possible to turn off MathJax globaly?

![image](https://cloud.githubusercontent.com/assets/6066764/22743461/8c12a1ce-ee1a-11e6-8ffe-1a74199a678a.png)

**Comment by F1LT3R** [comment]
Should be fixed now. (https://github.com/F1LT3R/markserv/pull/14)

Could you `npm install markserv -g` to confirm?

Thanks.

**Comment by calaveraInfo** [comment]
Yes, I can confirm it's fixed.
