### ISSUE TITLE
File name contain Chinese characters will cause 404 error

### ISSUE THREAD

**Issue by Rocky-Lee** [markserv/markserv#17]

**Comment by ChenYingChou** [comment]
According to https://github.com/F1LT3R/markserv/pull/18/files, the changes are as follows:

```diff
--- server-bak.js	2018-04-19 22:24:40.000000000 +0800
+++ server.js	2018-04-19 22:24:05.000000000 +0800
@@ -316,7 +316,7 @@
 	const dir = flags.dir

 	return (req, res) => {
-		const originalUrl = getPathFromUrl(req.originalUrl)
+		const originalUrl = getPathFromUrl(decodeURIComponent(req.originalUrl))

 		if (flags.verbose) {
 			msg('request')
```

**Comment by F1LT3R** [comment]
Ok, this should have been taken care of: https://github.com/F1LT3R/markserv/pull/18

![screen shot 2018-04-19 at 2 07 37 pm](https://user-images.githubusercontent.com/1218446/39010254-0e0cdd08-43dc-11e8-96d5-38ff632564ab.png)

Can you `npm i -g markserv`, navigate to the `examples/测试.md` and check that things look as you would expect?

If everything looks good. Feel free to close this issue.
