### ISSUE TITLE
Install failing: Command failed: /usr/local/bin/git checkout 5f0b3799f50944bc4d1eb58acdef61c38883d6cf

### ISSUE THREAD

**Issue by imhoffd** [markserv/markserv#19]
npm install is failing due to a git dependency. It's weird because I see the commit here: https://github.com/LearnBoost/websocket.io/commit/5f0b3799f50944bc4d1eb58acdef61c38883d6cf

```
$ npm install markserv -g
npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git checkout 5f0b3799f50944bc4d1eb58acdef61c38883d6cf
npm ERR! fatal: reference is not a tree: 5f0b3799f50944bc4d1eb58acdef61c38883d6cf
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dan/.npm/_logs/2017-07-24T16_18_09_255Z-debug.log
```

Anyone else getting the same issue?

**Comment by imhoffd** [comment]
More info:

I tried to `git clone git@github.com:LearnBoost/websocket.io.git` and then `git fetch origin 5f0b3799f50944bc4d1eb58acdef61c38883d6cf`, but got the error:
```
error: Server does not allow request for unadvertised object 5f0b3799f50944bc4d1eb58acdef61c38883d6cf
```

Workaround:

I instead downloaded a zip (https://github.com/LearnBoost/websocket.io/archive/5f0b3799f50944bc4d1eb58acdef61c38883d6cf.zip), did `npm install`, `npm link`, cloned `markserv` locally and did `npm link websocket.io`, `npm install`, `npm link` and I have the `markserv` binary globally.

Lots of work, but worth it for this useful tool.

@F1LT3R please consider ditching `websocket.io` for `ws` or something.

**Comment by xocasdashdash** [comment]
i managed to fix this issue by downgrading to node 7 and npm 4

**Comment by Sarafian** [comment]
@dwieeb I'm trying to follow your workaround but I get the same error. This is what I do and I'm no expert with node.

In `C:\Users\asarafian\Building MarkServ` I've downloaded 

- https://github.com/LearnBoost/websocket.io/archive/5f0b3799f50944bc4d1eb58acdef61c38883d6cf.zip
- https://github.com/F1LT3R/markserv/archive/master.zip

Then extracted respectively to their own directory with the module name and made sure the root of the contents are within each folder. 

- C:\Users\asarafian\Building MarkServ\websocket.io
- C:\Users\asarafian\Building MarkServ\markserv

From inside `C:\Users\asarafian\Building MarkServ\websocket.io` I executed:

1. `npm install`
1. `npm link`

From inside `C:\Users\asarafian\Building MarkServ\markserv` I executed:

1. `npm link websocket.io` that verifies with 
> C:\Users\asarafian\Building MarkServ\markserv\node_modules\websocket.io -> C:\Users\asarafian\AppData\Roaming\npm\node_modules\websocket.io -> C:\Users\asarafian\Building MarkServ\websocket.io
2. `npm install` which fails with the same error 

```text
908 silly resolveWithNewModule marked@0.3.2 checking installable status
909 silly fetchPackageMetaData error for websocket.io@git://github.com/LearnBoost/websocket.io.git#5f0b3799f50944bc4d1eb58acdef61c38883d6cf Command failed: C:\Program Files\Git\cmd\git.EXE checkout 5f0b3799f50944bc4d1eb58acdef61c38883d6cf
909 silly fetchPackageMetaData fatal: reference is not a tree: 5f0b3799f50944bc4d1eb58acdef61c38883d6cf
910 verbose stack Error: Command failed: C:\Program Files\Git\cmd\git.EXE checkout 5f0b3799f50944bc4d1eb58acdef61c38883d6cf
910 verbose stack fatal: reference is not a tree: 5f0b3799f50944bc4d1eb58acdef61c38883d6cf
910 verbose stack
910 verbose stack     at ChildProcess.exithandler (child_process.js:270:12)
910 verbose stack     at emitTwo (events.js:125:13)
910 verbose stack     at ChildProcess.emit (events.js:213:7)
910 verbose stack     at maybeClose (internal/child_process.js:927:16)
910 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

From the top of the log file the node and npm versions are:
```text
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.3.0
3 info using node@v8.5.0
```

Unfortunately I can't downgrade to previous versions.

**Comment by matchavez** [comment]
+1 install failure. Is this abandoned?

**Comment by imhoffd** [comment]
FWIW I use grip now https://github.com/joeyespo/grip

**Comment by Sarafian** [comment]
@dwieeb problem with anything that depends on github API is throttling. I used [MarkdownPS](https://www.powershellgallery.com/packages/MarkdownPS/1.4) to easily generate markdown pages from PowerShell and then serve them for multiple people. GitHub API based solutions quickly run into the throttling issue.

**Comment by F1LT3R** [comment]
Will try and get to this asap.

**Comment by petulla** [comment]
This repo works with @tuvistavie's [fork](https://github.com/tuvistavie/markserv.git).

`npm install https://github.com/tuvistavie/markserv.git -g`

**Comment by F1LT3R** [comment]
This should be fixed now. Apologies for the wait.

- Changes are in Master
- Published to NPM

Could you `npm install -g markserv` and let me know if it's behaving correctly for you too?

**Comment by sainiaditi** [comment]
try
`` npm install npm -g``
then do
`` npm install -g markserv ``
