### ISSUE TITLE
No Content-Type header

### ISSUE THREAD

**Issue by OLDlayeratwork** [markserv/markserv#23]
If I use `wget -S` to see the headers that come back from `markserv`, I see no `Content-Type` header.  This is causing Solr `post` from 7.0.1 to throw an exception.  Seems like that header should be present, since HTML is being served, right?

**Comment by F1LT3R** [comment]
Yeah, you are right. I will try and get to this.

**Comment by OLDlayeratwork** [comment]
I don't really care about this, except in the greater context of the search project you're doing.  I think it was before you started that project and I was playing around trying to figure it out on my own.  (And I didn't get far at all.)

**Comment by F1LT3R** [comment]
This should have been taken care of in PR https://github.com/F1LT3R/markserv/pull/34

```shell
$ wget -S localhost:8642

# --2018-04-25 23:36:13--  http://localhost:8642/
# Resolving localhost (localhost)... ::1, 127.0.0.1, fe80::1
# Connecting to localhost (localhost)|::1|:8642... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:8642... connected.
# HTTP request sent, awaiting response...
#   HTTP/1.1 200 OK


#   content-type: text/html


#   Date: Thu, 26 Apr 2018 03:36:13 GMT
#   Connection: keep-alive
#   Transfer-Encoding: chunked
# Length: unspecified [text/html]
# Saving to: ‘index.html’
# 
# index.html                [ <=>                      ]  14.81K  --.-KB/s    in 0s
# 
# 2018-04-25 23:36:13 (117 MB/s) - ‘index.html’ saved [15163]
```

Can you confirm?
