### ISSUE TITLE
NPM still links to 'legacy' repo

### ISSUE THREAD

**Issue by ukch** [markserv/markserv#27]
When visiting [the NPM page for markserv](https://www.npmjs.com/package/markserv), the 'GitHub' link points to the old 'legacy' URL. The offending line from package.json is below:

https://github.com/F1LT3R/markserv/blob/20620a5c17c71aa84f0560a33e318ea7e67eb4e6/package.json#L22

**Comment by F1LT3R** [comment]
Fixed.

https://github.com/F1LT3R/markserv/blob/master/package.json#L22
