### ISSUE TITLE
Reduce number of gifs on README

### ISSUE THREAD

**Issue by antitoxic** [markserv/markserv#3]
Cool project! Exactly what I needed to have interactive docs.

However every time I go to https://github.com/F1LT3R/markserv/ my Chrome crashes. I bet it's because of the gifs.

I suggest to lower the resolution and make some of them external.

**Comment by F1LT3R** [comment]
Thanks @antitoxic! Do you want to create a PR removing the animated Gif?

**Comment by F1LT3R** [comment]
Switched to non-animated GIFs. Animations can be watched by clicking on the image.
