### ISSUE TITLE
Markdown Tables not rendering

### ISSUE THREAD

**Issue by sigmasoldi3r** [markserv/markserv#30]
Tables are not being rendered, using example code from _GitHub_ [https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables)

Sample code used:
```md
Colons can be used to align columns.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

There must be at least 3 dashes separating each header cell.
The outer pipes (|) are optional, and you don't need to make the
raw Markdown line up prettily. You can also use inline Markdown.

Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
```

What renders:
![image](https://user-images.githubusercontent.com/13834659/38919106-ef07aa9c-42ef-11e8-8bba-a6f030e4c136.png)

Expected result: (Markdown tables rendered properly)
* * *
Colons can be used to align columns.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

There must be at least 3 dashes separating each header cell.
The outer pipes (|) are optional, and you don't need to make the
raw Markdown line up prettily. You can also use inline Markdown.

Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
* * *

**Comment by F1LT3R** [comment]
Thanks. Were you aware of this working previously? I'm trying to figure out if this was a regression that appeared after updating to use commonMark.

**Comment by F1LT3R** [comment]
This should be fixed now.
https://github.com/F1LT3R/markserv/pull/31

Can you confirm?

### Steps

- Re-install markserv `npm i -g markserv`
- Start the markserv server `markserv`
- Navigate to `/tests/tables.md`
- Check that the tables look as you expect them to

**Comment by sigmasoldi3r** [comment]
Great! 🎉 Now is working fine, Very quick bug fixing there! 👌

![image](https://user-images.githubusercontent.com/13834659/38994613-26c8c93c-43e7-11e8-9ae4-9593a3a84c45.png)
