### ISSUE TITLE
Too slow to open marksrv server page.

### ISSUE THREAD

**Issue by m2acgi** [markserv/markserv#38]
It's very slow to load the page served by markserv server. After check the Chrome developer tools, I found the root cause it that http request to `http://sindresorhus.com/github-markdown-css/github-markdown.css` failed. 

In my network, we can't access the url becase of internet censorship.

![2018-05-02 17_22_34-greenshot](https://user-images.githubusercontent.com/34497122/39516080-6d332a9c-4e2e-11e8-9337-84770f1da84a.png)

**Comment by F1LT3R** [comment]
Thanks for submitting @m2acgi - I will look into this today. What I might do is bundle this file internally with markserv so it gets packaged in the published tarball on npm.

**Comment by F1LT3R** [comment]
Should be fixed now in markserv@1.6.1 - see: https://github.com/F1LT3R/markserv/pull/40

@m2acgi could you `npm i -g markserv@1.6.1` and let me know if things are working for you now?

**Comment by m2acgi** [comment]
@F1LT3R 

Things are working. But there's another issue, I can't run markserv with the command "markserv -a 0.0.0.0 /docs". but put this command to /etc/rc.local, then reboot, it works.

![2018-05-03 15_58_21](https://user-images.githubusercontent.com/34497122/39565677-73bbb5f6-4eeb-11e8-8db3-ff40b1ad017c.png)

**Comment by F1LT3R** [comment]
Try putting s period before the slash `markserv -a 0.0.0.0 ./docs`

Using `/docs` would look for the directory on the root of your drive.

**Comment by F1LT3R** [comment]
Oh you do have docs in root. That's interesting. If you `cd /docs` and `markserv -a 0.0.0.0 ./`, what happens?

**Comment by m2acgi** [comment]
If I 'cd /docs' and 'markserv -a 0.0.0.0 ./', it works.

**Comment by F1LT3R** [comment]
Thanks for checking this. I will look into it soon. If it works fine the same dir it's most likely a confirmation problem in my code.

Thanks for looking into this :raised_hands:

**Comment by F1LT3R** [comment]
Let's tackle this bug here: https://github.com/F1LT3R/markserv/issues/46

**Comment by F1LT3R** [comment]
Do you mind if we close this first bug now @m2acgi ?

**Comment by m2acgi** [comment]
@F1LT3R  ok, thank you.
