### ISSUE TITLE
Base URL

### ISSUE THREAD

**Issue by mykiimike** [markserv/markserv#39]
Possibility to setup a base URL directory useful when you serve files from another directory (/manual for instance).
By using rewrite on a proxy server the rules links are still pointing on /

**Comment by F1LT3R** [comment]
Would the base url you are thinking of be used by the users? I'm asking because I'm already using a base url internally to fetch internal resources.

How would you think to specify this? CLI arg/flag?

**Comment by F1LT3R** [comment]
Closing (no feedback).
