### ISSUE TITLE
feature request: table

### ISSUE THREAD

**Issue by m2acgi** [markserv/markserv#41]
I'm using the chrome extentios named "Markdown Preview Plus" on my local PC. There's a feature called table, it's very convenience when read the .md docs.

Could you pls add this feature to markserv ?

Thank you for your great software!

![2018-05-03 16_09_13-greenshot](https://user-images.githubusercontent.com/34497122/39566038-c618d0ee-4eec-11e8-8a40-f0d04ae94e02.png)

**Comment by F1LT3R** [comment]
I will look into this table feature and let you know.

**Comment by m2acgi** [comment]
Thank you. Looking forward to adding this feature.

**Comment by F1LT3R** [comment]
@m2acgi, did this work for you?

**Comment by m2acgi** [comment]
@F1LT3R It works, perfect! Thank you very much.

![2018-05-04 09_34_59](https://user-images.githubusercontent.com/34497122/39609884-d35f08c6-4f7e-11e8-80b0-052acc3a96ff.png)
