### ISSUE TITLE
Support default index page

### ISSUE THREAD

**Issue by sandinmyjoints** [markserv/markserv#57]
This is a useful project, thanks! Here's my issue: my repo's entrypoint is README.md. When I start markserv, I'd like http://localhost:8642/ to show the contents of README.md, so I created index.html with this content:

```
{markdown: ./README.md}
```

However, when I start `markserv .` and go to http://localhost:8642/, I see a directory listing of files. I expected to sees the rendered contents of README.md.

When I browse directly to http://localhost:9999/index.html, I see the contents of README.md rendered as html, but without the styling -- none of the css files are loaded.

I tried changing index.html to this content, in case this issue was related to inline markdown rendering:

```html
<html>
  <body>
    <h1>content</h1>
  </body>
</html>
```

But it had the same result.

**Comment by F1LT3R** [comment]
What if you just type "readme" from anywhere in your projects tree? Does that launch your Readme?

**Comment by e40** [comment]
> What if you just type "readme" from anywhere in your projects tree? Does that launch your Readme?

It does not for me.  When I launch with `markserv README.md` and go to `http://localhost` it shows the directory listing where `README.md` exists.
