### ISSUE TITLE
Some steps to make it "production" server

### ISSUE THREAD

**Issue by smnbbrv** [markserv/markserv#62]
Hi,

just found your tool, it looks super!

Could you please add flag(s) to disable livereload and opening the browser? I am running this in docker, so those options are totally irrelevant to me.

Also, there (maybe) should be a way to hide PID footer

**Comment by F1LT3R** [comment]
You can hide the PID footer by using the templating system. Though I think your use case is to not have to do any templating and use it with the default styles "as-is".

If you find you **really** want the PID removal option, could you submit a new Issue?

**Comment by F1LT3R** [comment]
Added you launch options in https://github.com/markserv/markserv/pull/65

The following should now work. Cna you verify?

```shell
markserv --livereloadport false --browser false
readme --livereloadport false --browser false
```

You will need to `npm i -g markserv@1.15.0`

**Comment by smnbbrv** [comment]
Wow that’s super fast 🙂I will check it as soon as I can 👍

**Comment by F1LT3R** [comment]
I was thinking about the PID thing... The reason it was there in the first place was that the PID was not output in the CLI. There was also no way to kill the server with CTRL+C back then.
At this point the PID in the HTML output is redundant, so I'm 100% on board with removing that.

**Comment by smnbbrv** [comment]
@F1LT3R  A (maybe) stupid question: why is it not possible to use Ctrl+C? This is also a quite annoying issue

**Comment by F1LT3R** [comment]
You can use CTRL+C. Is this not working for you?

**Comment by smnbbrv** [comment]
nope, see:

Simplest docker config

```
FROM node:latest

EXPOSE 80

RUN npm i -g markserv

COPY docs /srv/docs

CMD exec markserv -p 80 -a 0.0.0.0 /srv/docs/
```

```sh
docker build -t markserv .
```

```sh
docker run -p 8080:80 markserv
```

and then no Ctrl + C is possible; I am forced to kill docker process after with `docker ps` and `docker kill id`

**Comment by smnbbrv** [comment]
I create another issue for this. Thanks!

**Comment by smnbbrv** [comment]
Thank you for the fixes btw! Works fine
