### ISSUE TITLE
Ctrl + C does not work in docker

### ISSUE THREAD

**Issue by smnbbrv** [markserv/markserv#66]
Simplest docker config

```
FROM node:latest

EXPOSE 80

RUN npm i -g markserv

COPY docs /srv/docs

CMD exec markserv -p 80 -a 0.0.0.0 /srv/docs/
```

```sh
docker build -t markserv .
```

```sh
docker run -p 8080:80 markserv
```

and then no Ctrl + C is possible; I am forced to kill docker process after with `docker ps` and `docker kill id`

**Comment by F1LT3R** [comment]
I'm assuming Ctrl + C works to kill other apps in Docker?

**Comment by F1LT3R** [comment]
I'm wondering if this is more of a docker issue thank a node issue? https://github.com/nodejs/node/issues/4182#issuecomment-396145697

**Comment by F1LT3R** [comment]
Yeah I do that in some other codebase. I wasn't aware that helped in Docker. (I rarely use docker). 

I'll look into it. Thanks for posting!

**Comment by smnbbrv** [comment]
Thank you for very positive behavior 🙂 that’s something I don’t meet that often

**Comment by F1LT3R** [comment]
I will try and find some time this week to get this working.

**Comment by ferk6a** [comment]
@smnbbrv I believe you have to use CMD with array syntax in order for that to work. Bash doesn't forward signals correctly. So it should be something like this:

```dockerfile
CMD ["exec", "markserv", "-p", "80", "-a", "0.0.0.0", "/srv/docs/"]
```

**Comment by smnbbrv** [comment]
nope, the comment is actually useless

however this solves the problem https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#handling-kernel-signals

Proper solution would be either to use tini or dumb-init
