### ISSUE TITLE
Image get 404 when the url parameter present

### ISSUE THREAD

**Issue by wyfdev** [markserv/markserv#7]
request url with parameter like:
    `http://localhost:8000/images/logo.jpg?raw=true`
get response " 404 :'( " with 200 status code.

**Comment by F1LT3R** [comment]
This is interesting, I see why that would happen. Why would you add ?raw=true? Are you running Markserv alongside something else?

**Comment by wyfdev** [comment]
I get this when i view a github repository READMD.md local ~
cause this https://stackoverflow.com/questions/13051428/how-to-display-images-in-markdown-files-of-github

**Comment by F1LT3R** [comment]
Ah, I see! Ok I will look into it.

**Comment by F1LT3R** [comment]
Should be fixed: https://github.com/F1LT3R/markserv/compare/fix-url-params?expand=1

**Comment by F1LT3R** [comment]
@WYFDEV try installing Markserv again and let me know if that works?

**Comment by wyfdev** [comment]
oh ~  I get the error message:

``` bash
/usr/local/lib/node_modules/markserv/server.js:102
  let extensionMatch = false;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

On my ubuntu 16.04  &  node@v4.2.6

**Comment by F1LT3R** [comment]
Which version of Node are you using? `node --version`

I'm using `v6.7.0`

I've added back `'Use Strict';` to invoke strict mode on older versions of Node.

Try re-installing again, it should work now regardless of your version. (Assuming you're not using a super-old version of Node).

**Comment by wyfdev** [comment]
OK!
Works good after update my node to v6.9.1
Thank you :+1:

**Comment by F1LT3R** [comment]
np, glad that helped
