### ISSUE TITLE
Increase default width of body

### ISSUE THREAD

**Issue by ptkdev** [markserv/markserv#73]
Hi,
Default css width of body is `45em` please increase to `55em`. Imho 45em is very low default value.

**Comment by F1LT3R** [comment]
What is it on GitHub?

**Comment by ptkdev** [comment]
How can I change this value? where can I find the template docs?

**Comment by ptkdev** [comment]
@F1LT3R I'm checked width of github website of README.md div element.
Github markdown width: `978px`
Markserv width: `720px`
My monitor resolution is `1920px`, imho `45em` don't is correct value on big monitor if you want **mirror GitHubs style** .

**Comment by F1LT3R** [comment]
You're welcome to submit a PR. I have been pulling GitHub styles from another repo. But it's possible that repo is no longer in sync with GitHub.

**Comment by F1LT3R** [comment]
Here's where I was getting my styles: https://github.com/sindresorhus/github-markdown-css

**Comment by F1LT3R** [comment]
That's all done and merged in [markserv@1.16.0](https://npmjs.com/markserv).

Can you let me know that things are working as you expect if you install latest markserv?
